# Generated by Django 6.0.4 on 2026-05-03 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_route', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelstation',
            name='opis_id',
            field=models.IntegerField(),
        ),
    ]
